/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiCandidat {}
  interface SpiCandidatAttributes extends StencilHTMLAttributes {}

  interface EnsAjouter {
    'home': RouterHistory;
  }
  interface EnsAjouterAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface EnsDetail {
    'match': MatchResults;
  }
  interface EnsDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnsRechercher {
    'match': MatchResults;
  }
  interface EnsRechercherAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnsSupprimer {
    'match': MatchResults;
  }
  interface EnsSupprimerAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SpiCandidat': Components.SpiCandidat;
    'EnsAjouter': Components.EnsAjouter;
    'EnsDetail': Components.EnsDetail;
    'EnsRechercher': Components.EnsRechercher;
    'EnsSupprimer': Components.EnsSupprimer;
    'SpiEnseignant': Components.SpiEnseignant;
    'SpiHeader': Components.SpiHeader;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'spi-candidat': Components.SpiCandidatAttributes;
    'ens-ajouter': Components.EnsAjouterAttributes;
    'ens-detail': Components.EnsDetailAttributes;
    'ens-rechercher': Components.EnsRechercherAttributes;
    'ens-supprimer': Components.EnsSupprimerAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLSpiCandidatElement extends Components.SpiCandidat, HTMLStencilElement {}
  var HTMLSpiCandidatElement: {
    prototype: HTMLSpiCandidatElement;
    new (): HTMLSpiCandidatElement;
  };

  interface HTMLEnsAjouterElement extends Components.EnsAjouter, HTMLStencilElement {}
  var HTMLEnsAjouterElement: {
    prototype: HTMLEnsAjouterElement;
    new (): HTMLEnsAjouterElement;
  };

  interface HTMLEnsDetailElement extends Components.EnsDetail, HTMLStencilElement {}
  var HTMLEnsDetailElement: {
    prototype: HTMLEnsDetailElement;
    new (): HTMLEnsDetailElement;
  };

  interface HTMLEnsRechercherElement extends Components.EnsRechercher, HTMLStencilElement {}
  var HTMLEnsRechercherElement: {
    prototype: HTMLEnsRechercherElement;
    new (): HTMLEnsRechercherElement;
  };

  interface HTMLEnsSupprimerElement extends Components.EnsSupprimer, HTMLStencilElement {}
  var HTMLEnsSupprimerElement: {
    prototype: HTMLEnsSupprimerElement;
    new (): HTMLEnsSupprimerElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'spi-candidat': HTMLSpiCandidatElement
    'ens-ajouter': HTMLEnsAjouterElement
    'ens-detail': HTMLEnsDetailElement
    'ens-rechercher': HTMLEnsRechercherElement
    'ens-supprimer': HTMLEnsSupprimerElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'spi-header': HTMLSpiHeaderElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'spi-candidat': HTMLSpiCandidatElement;
    'ens-ajouter': HTMLEnsAjouterElement;
    'ens-detail': HTMLEnsDetailElement;
    'ens-rechercher': HTMLEnsRechercherElement;
    'ens-supprimer': HTMLEnsSupprimerElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
